### PR TITLE
Minor Improvements

### PR DESCRIPTION
**Pull request by mvuljevas**
- Fixed output for template files
- Fixed path for locales
- Updated devDependencies

### CODE REVIEW

**Review by 3daddict — APPROVED** [review]
Thanks @mvuljevas for the contribution! These changes look good.

**Comment by 3daddict** [comment]
@mvuljevas thanks for contributing here. What do you think of this setup?
It's still a work in progress but I think it has merit.
Let me know what you think any and all feedback is welcome.

**Comment by mvuljevas** [comment]
> @mvuljevas thanks for contributing here. What do you think of this setup?
> It's still a work in progress but I think it has merit.
> Let me know what you think any and all feedback is welcome.

Hey @3daddict, this approach is one of the best we found on the web!, for you to have an idea, we took this model, and we're building a DevTools that will make all the compile process and deployments automatically based on this approach.

Apart from that, thank you very much for merge my little contribution, I will continue working based on this and will ping you if something good arrives!

**Comment by 3daddict** [comment]
Very happy to hear that @mvuljevas thanks for that great feedback and I am excited to see what you make with this approach. Feel free to add ideas as issues in this repo. I am hoping to gain some traction and contributors to this one to make something cool and easy to work with.

Right now I am searching for a way to remove all newlines and empty whitespace when compiling. Essentially minimizing liquid files but I have not found anything that can do it.

**Comment by mvuljevas** [comment]
> Very happy to hear that @mvuljevas thanks for that great feedback and I am excited to see what you make with this approach. Feel free to add ideas as issues in this repo. I am hoping to gain some traction and contributors to this one to make something cool and easy to work with.
> 
> Right now I am searching for a way to remove all newlines and empty whitespace when compiling. Essentially minimizing liquid files but I have not found anything that can do it.

You're more than welcome @3daddict!, I'll keep posted for sure!, maybe we can continue the talk with other platform?, you can find me on linkedin if you want to talk and know a more about what we're building, I think you will love it

**Pull request merged**
